# Generated by Django 3.1 on 2021-02-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
